### ISSUE TITLE
support mapping of tasks.json task_id values to ptc task_ids `text` entries

### ISSUE THREAD

**Issue by matthewcornell** [hubverse-org/hub-dashboard-predtimechart#25]
Currently the code that uses task_id values from a hub's tasks.json to generate predtimechart's [options object's](https://github.com/reichlab/predtimechart?tab=readme-ov-file#options-object) `task_ids` does not provide a `text` entry for each value. Instead the code uses the value itself for both `value` and `text` (see [this line](https://github.com/hubverse-org/hub-dashboard-predtimechart/blob/cebc571522c024db22da171983776f3ce5e546bb/src/hub_predtimechart/generate_options.py#L21)):

```python
    for task_id, task_values in hub_config.fetch_task_ids.items():  # ex: {'location': ["US", "01", ...], ...}
        options['task_ids'][task_id] = [{'value': task_value, 'text': task_value} for task_value in task_values]
```

The result is that (for FIPS-based _locations_) the generated task ID dropdown shows the code for both (e.g., "25") instead of the corresponding human-readable text (e.g., "Massachusetts").

The solution is for the hub dashboard owner to provide a mapping of task_id values to text for each task_id that's in the viz. The mapping could be placed directly in predtimechart-config.yml, or in a file (json?) that an entry in the config points to. For the former, it might look something like:

```yaml
---
rounds_idx: 0
model_tasks_idx: 2
...
task_id_value_to_text:
  location:
    US: US
    01: AL
    ...
    78: VI
...
```

REF:
- Slack thread where @zkamvar brought this up : https://reichlab.slack.com/archives/C07LDJF5GTZ/p1730838310059099

**Comment by zkamvar** [comment]
> The solution is for the hub dashboard owner to provide a mapping of `task_id` values to text for each `task_id` that's in the viz. 

I agree this is the most straightforward solution. What do you think about using `task_id_text` or `task_id_dict` as the key instead of `task_id_value_to_text`?

**Comment by matthewcornell** [comment]
I like `task_id_text`.

**Comment by elray1** [comment]
1. Yeah, let's make it optional.  If it's not provided, behavior will be as now: the task id value is also used as the text
2. Where are you thinking of adding this?  For the [specific config file FluSight dashboard](https://github.com/reichlab/flusight-dashboard/blob/main/predtimechart-config.yml), it probably makes sense to pull from the [source in the cdcepi repo](https://github.com/cdcepi/FluSight-forecast-hub/blob/main/auxiliary-data/locations.csv) (though the contents should be the same as the file you had linked to).  I'm not sure it makes sense to add these kinds of settings to the general or template repos though?

**Comment by matthewcornell** [comment]
2. My thinking was to do a one-time extraction of those values from that file (instead of the linked one) and then add them in the correct format to the [specific config file for the FluSight dashboard](https://github.com/reichlab/flusight-dashboard/blob/main/predtimechart-config.yml).

**Comment by elray1** [comment]
sounds good!
